Error message for repo creation when file exits
When a file with the repo name exists in $GITHOME, exit with an error message.

diff --git a/gitreceive b/gitreceive
--- a/gitreceive
+++ b/gitreceive
@@ -81,6 +81,10 @@ parse_repo_from_ssh_command() {
 ensure_bare_repo() {
   declare repo_path="$1"
   if [ ! -d "$repo_path" ]; then
+    if [ -e "$repo_path" ]; then
+      echo 'Fatal error: invalid repository name.' > /dev/stderr
+      exit 1
+    fi
     mkdir -p "$repo_path"
     cd "$repo_path"
     git init --bare > /dev/null
